# Generated by Django 5.0.2 on 2024-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
