# Generated by Django 5.0.2 on 2024-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_prayerrequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
