# Generated by Django 5.0.2 on 2024-03-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_event_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='is_removed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='is_removed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_removed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='is_removed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
